# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NomzV2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0.0-rc.1'

  target 'NomzV2Tests' do
    inherit! :search_paths
    pod 'Alamofire', '~> 5.0.0-rc.1'
  end

end
